# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ 1.7-TiM ]
  pull_request:
    branches: [ 1.7-TiM ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Cache gradle dependencies
      uses: actions/cache@v2.1.3
      with:
        path: |
          ~/.gradle
        key: ${{ runner.os }}-gradle

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew setupDecompWorkspace --refresh-dependencies build

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: Traincraft-5-Experimental
        path: build/libs/*
